### ISSUE TITLE
Ensure addon is compatible with 7.5 release

### ISSUE THREAD

**Issue by ashleyse2016** [SpamExperts/whmcs-addon#10]
As WHMCS 7.4 is released we should verify that the addon is fully compatible. 

Some reports of WHMCS "hanging" on provisioning of domains. While the domains get added correctly via the API WHMCS itself seems to hang.

**Comment by lorentina** [comment]
During testing I found that after upgrading to whmcs 7.4 our addon is not visible anymore (and does not appear to be installed on whmcs testing server).
Installing the addon on a freshly upgraded whmcs testing server does not throw any errors, but when executing the Create/Terminate command for a product, it does not show any success/error message, instead the "Working..." loading sign is shown indefinitely.

**Comment by nicolaeSE** [comment]
The issue with addon missing after upgrade may be due to the way you upgraded whmcs (maybe trough some custom script).
I was able the get everything running on a freshly upgraded server with no obvious issues whatsoever.
Please test this again.

**Comment by lorentina** [comment]
@nicolaeSE: re-tested the addon on whmcs 7.4 using the steps provided. No issues were encountered during testing on a freshly upgraded server or when the upgrade was done on a server that already had clients and products.

**Comment by scardus** [comment]
Has the plugin been tested/updated to support WHMCS v7.5 yet?  We need to upgrade ASAP but this Github issue has us concerned we're going to encounter problems...

**Comment by lorentina** [comment]
No major issues were encountered while testing the addon on whmcs 7.5.
However, there is a small inconvenient when users are accessing their client area, and go to one of their Active Products/Services: first, the management buttons are displayed correctly, but if the user clicks on Management option from the Actions menu in the left then buttons are shown without any text. 
Also clicking the Information option from the Overview menu in the left will make the management buttons disappear. Going back to main page on client area and selecting the product to be managed will make the buttons show up as expected.

**Comment by donici** [comment]
@claudiapetre can you have someone look into the issue Lorentina mentioned above?

**Comment by lorentina** [comment]
Fix verified.
