### ISSUE TITLE
Status pending even though the domain gets added

### ISSUE THREAD

**Issue by SebaDA** [SpamExperts/whmcs-addon#11]
### Version information

- WHCMS:  version 7.5 
- Addon: latest version

### Steps to replicate

 1.     Go the customer, go to the SpamExperts product.
 2.    Click Create.
 3.   WHMCS now stays at "Working..." instead of saying Success.

### Actual result

Domain gets added but status pending

### Expected result

Status to show: succcess

### Other notes
This is the API response when I execute the Create command:
Array
(
[messages] => Array
(
[success] => Array
(
[0] => 'Outgoing email filtering' has been disabled for the domain 'example.com'
[1] => Domain timezone updated successfully
[2] => Administrator's contact email for the domain 'example.com' is changed to 'example@example.com'
[3] => Domain 'example.com' added
)

    )

[result] => 

341713

**Comment by nicolaeSE** [comment]
This most likely happens due to the fact that we did have a release with the #10 changes that ensure the compatibility the latest upgrades.

**Comment by claudiapetre** [comment]
The issue was fixed after the last release.
