### ISSUE TITLE
Log In to Panel option does not allow log in

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/whmcs-addon#12]
### Version information
7.1.1

### Steps to replicate

 1. Client tries to login to spampanel via "Log In To Panel" from their WHMCS client portal
 2. The client is redirected to another site

### Expected result
The client should be able to login

### Other notes
WHMCS: https://my.spamexperts.com/admin/supporttickets.php?action=view&id=211358

**Comment by claudiapetre** [comment]
The issue can't be replicated on our testing servers. Please, check, if for the Spam Panel admin used in addon module, "Allow control panel API usage" is checked.
