### ISSUE TITLE
Error creating user with a "#" in the password

### ISSUE THREAD

**Issue by javildn** [SpamExperts/whmcs-addon#14]
### Version information
Latest.

### Steps to replicate

Create a reseller user using the module with a "#" in the password.

### Actual result

The user is not created, but it says it is Ok.

### Expected result

Throw an error or enhance the module to accept "#" in the password

**Comment by claudiapetre** [comment]
The API doesn't allow to use # inside password value. A ticket was open and it will be solved there.

**Comment by dmitry-lomakin** [comment]
The API acts correctly here - in order to be accepted a password containing special characters must be URL-encoded

**Comment by lorentina** [comment]
Verified "#" is an accepted character in a reseller/domain user password. The module creates the user as expected.
