### ISSUE TITLE
Panel Login Button Missing Values

### ISSUE THREAD

**Issue by deletethisuserplease** [SpamExperts/whmcs-addon#15]
### Version information
WHMCS: 7.4.2-release.1
PHP:  5.6.30
Curl:  7.19.7
Addon Version:  1.0
SpamExperts Version:  138072

### Steps to replicate

 1.  Log into client area for customer.
 2.  Go to the spam experts product.
 3.  Click the "Log In To Panel" button or review the page's HTML code.

### Actual result
"Log In To Panel" button's value is only a window.open function set to "/?authticket=".  No domain prior to the "/" and no ticket after the "=".

### Expected result
"Log In To Panel" button takes client to SpamExperts control panel when clicked.

### Other notes
This same module is working on a system with almost identical specifications except the following differences observed:
 1.  It has PHP 5.6.22; non-working site has 5.6.30.
 2.  It has PHP Json module version 1.3.9; non-working site has 1.3.10.
 3.  It has a memory limit value of 256M; non-working site has 128M.
 4.  It has ionCube PHP Loader 5.1.2; non-working site has 10.2.0.

**Comment by dbistriceanu** [comment]
This looks a lot like a config issue. 
Can you please check if:
 * on the Configuration tab there is a valid config set (hostname, username and password) and Test connection returns Success and on the Support tab theSpamExperts API Connection shows as OK (this is mandatory for the WHMCS addon, and Log In To Panel action, to work)
 * the domain listed on the SpamExperts product page in the Client Area is actually present in the SpamExperts system and belongs to the admin that has been configured for the WHMCS addon (the Log In To Panel action will try to log in as that Domain user, so if it doesn't exist or doesn't belong to the configured admin it will fail)

**Comment by claudiapetre** [comment]
After the investigation, the conclusion was that this is a config issue. 
Few suggestions were made to the client, but they were not confirmed/invalidated.
This ticket will be closed for inactivity reasons.

**Comment by deletethisuserplease** [comment]
@dbistriceanu Sorry on the delay.
1.) Yes, clicking the "Test Connection" button does return a "Success" status next to the "Test Connection" button.  Under the "Support" tab of the module I see "OK" for all items, including "SpamExperts API Connection".
2.) If I go to the "Show All" link under the "My Products" section of the Spam Experts Client Area, I see our "Webhosts - Hosted Cloud" product listing.  What domain exactly am I looking for?  Am I looking for the base domain of the WHMCS installation using the module?  Do I need to log in to the control panel for the hosted cloud product and look for a domain there?

**Comment by deletethisuserplease** [comment]
@dbistriceanu @tonyandrewmeyer @claudiapetre Is it possible to reopen this now that I've added the details in my last comment?
