### ISSUE TITLE
Compatibilty with PHP 7.X

### ISSUE THREAD

**Issue by javildn** [SpamExperts/whmcs-addon#17]
### Version information
Latest

### Steps to replicate

The code is using mysql_ functions that were deleted with PHP 7.X. The latest PHP version that this code works is PHP 5.6 and PHP 5.6 will be EOL in 12 days (31 Dec 2018). So I think it is urgent to have an upgrade on the code to support current PHP versions.

**Comment by LaurentiuTeodorescu** [comment]
From [MMA-5757](https://n-able.atlassian.net/browse/MMA-5757) - Update WHMCS Addon for the latest WHMCS version
```
WHMCS Version	8.2.1-release.1
PHP Version	7.3.29-1~deb10u1
Curl Version	7.64.0
Addon Version	1.0
SpamExperts Version	20210823.09
```
Done in https://github.com/SpamExperts/whmcs-addon/pull/18
