### ISSUE TITLE
The WHMCS addon is not accepting the & character in the passwords

### ISSUE THREAD

**Issue by SebaDA** [SpamExperts/whmcs-addon#4]
### Version information
WHMCS Version 	7.1.2-release.1
PHP Version 	7.0.18
Curl Version 	7.36.0
Addon Version 	1.0

### Steps to replicate

 1. Add an administrator with a password containing & character in it Eg: test&123
 2. Install the addon
 3. Go to configure and add all details.
 4. Save the configuration
 5. Go to the Support tab - it will show the `Supplied credential is invalid.` error

### Actual result

`Supplied credential is invalid. ` error returned

### Expected result

`OK` response

### Other notes

% Character is accepted, but not sure if any other special characters lead to the same issue.

**Comment by georgianiorgu1** [comment]
The issue couldn't be reproduced after the fix implemented in this ticket.

Fix verified.
