### ISSUE TITLE
Verify addon works in WHMCS 7.2.1 

### ISSUE THREAD

**Issue by ashleyse2016** [SpamExperts/whmcs-addon#5]
The addon needs to be verified in the lastest WHMCS 7.2.1  version.  Some reports of this not working. And erroring our with things like this on the product/services page

```
Error: Whoops\Exception\ErrorException: Undefined offset:1 in /home/admin/domains/example.com/public_html/clients/example/configproducts.php:0 Stack trace: #0 /home/admin/domains/example.com/public_html/clients/example/configproducts.php(0): Whoops\Run->handleError(8, 'Undefined offse...', '/home/admin/dom...', 0, Array) #1 {main}
```

**Comment by ghost** [comment]
Any ETA on this?

**Comment by Radiant-Solutions** [comment]
7.2.2 was just released it corrected the crashing of the products and service page, as well as the clients ability to click and manage the product. Now once the clients clicks to manage product there is no boxes to manage the spamexperts domain.

**Comment by georgianiorgu1** [comment]
I've tested the addon with Whmcs Version: 7.2.2 (template version Six).

Everything worked as intended and the initial errors weren't reproducible.
