### ISSUE TITLE
Small typo in ConfigOption

### ISSUE THREAD

**Issue by bady1985** [SpamExperts/whmcs-addon#9]
### Steps to replicate

Go to the product settings (module tab) and activate the checkboxes "Allow users to manage their routes" and/or "Allow users to change their contact details" and go to the clientarea. 
If you activate the checkbox "Allow users to change their contact details" he can't change the contact details, if you uncheck the checkbox he can, the same with the other checkbox.

**Comment by lorentina** [comment]
Verified that checkboxes work according to their current labels.

**Comment by tonyandrewmeyer** [comment]
Not published, cannot be closed.

**Comment by donici** [comment]
@lorentina, please double check this again to see if everything still works.

**Comment by lorentina** [comment]
Re-verified. Everything works fine.
